name: train-my-model

on:
  push:
  schedule:
    - cron: "0 0-23 * *"

jobs:
  run:
    runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: iterative/setup-cml@v1

      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: cml
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install -r requirements.txt
          python getting_data.py
          python train.py

          cat performance.csv >> report.md
          cml-send-comment report.md
