name: train-my-model

on:
  push:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: iterative/setup-cml@v1

      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: cml
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip3 install -r requirements.txt
          python getting_data.py
          python train.py

          cml publish difference.png --md >> report.md
          cml publish last_hour.png --md >> report.md
          cml-send-comment report.md
