name: Air-quality 
on: [push] 
jobs:  
  run:    
    runs-on: [ubuntu-latest]     
    steps:      
      - uses: actions/checkout@v2       
      - uses: iterative/setup-cml@v1      
      - uses: actions/setup-python@v2
      - with: {python-version: '3.x'}
      - name: Train model
        run: |
          pip3 install -r requirements.txt
          python train.py        
      - name: cml report
        env: 
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |         
            echo "## Model Metrics" > report.md
            cat metrics.csv >> report.md

