name: Air-quality 
on: [push] 
jobs:  
  run:    
    runs-on: [ubuntu-latest]     
    steps:      
      - uses: actions/checkout@v2       
      - uses: iterative/setup-cml@v1      
      - uses: actions/setup-python@v2
        with: {python-version: '3.x'}
        
      - name: cml
        run: |
            pip3 install -r requirements.txt
            python train.py

            echo "## Model Metrics" > report.md
            cat metrics.csv >> report.md

